-- AlterTable
ALTER TABLE "Article" ALTER COLUMN "writer" DROP NOT NULL,
ALTER COLUMN "writer" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "writer" DROP NOT NULL,
ALTER COLUMN "writer" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "image" DROP NOT NULL,
ALTER COLUMN "image" DROP DEFAULT,
ALTER COLUMN "writer" DROP NOT NULL,
ALTER COLUMN "writer" DROP DEFAULT;
