GET http://localhost:3000/products

###
GET http://localhost:3000/products?sort=recent&keyword=갤럭시

###
GET http://localhost:3000/products/0486722d-02f8-4a40-bdb0-0bfb2dfaeb70

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"갤럭시 S40",
  "description":"쌈송에서 만든 최신 폰",
  "price":990000,
  "tags":["갤럭시", "삼성"]
}

###
PATCH  http://localhost:3000/products/0486722d-02f8-4a40-bdb0-0bfb2dfaeb70
Content-Type: application/json

{
  "name":"갤럭시 S50",
  "price":5400
}