GET http://localhost:5500/products?limit=0

###
GET http://localhost:5500/products?sort=recent&keyword=갤럭시

###
GET http://localhost:5500/products/67471f9a567ff59e02673443

###
POST http://localhost:5500/products
Content-Type: application/json

{
  "name":"아이폰 4",
  "description":"맥북에 최적화, 가성비보단 품격",
  "price":5800000,
  "tags":["모니터", "델"]
}

###
PATCH  http://localhost:5500/products/67473d83cbe51c41f5f3e271
Content-Type: application/json

{
  "favoriteCount":"13"
}