###
POST http://localhost:5500/articles
Content-Type: application/json

{
  "title":"돌겠다 S40",
  "content":"쌈송에서 만든 최신 폰"
}

###
POST http://localhost:5500/post
Content-Type: application/json

{
  "title":"포스트 S40",
  "content":"쌈송에서 만든 최신 폰"
}

###
PATCH  http://localhost:5500/articles/8ab7c05d-c252-49e0-a9e0-e5d76ba4b558
Content-Type: application/json

{
  "title":"글이 잘 작성되는건가요..게시판!!!",
  "content":"냉무 ㅋ아 너무 짧으면 안 되는구나 ㅠㅠ"
}

###
GET http://localhost:5500/articles/0456b46f-7a18-4211-b7a1-2216f84cc2cb

###
GET http://localhost:5500/articles?limit=20

###
POST http://localhost:5500/articles/0456b46f-7a18-4211-b7a1-2216f84cc2cb/comments
Content-Type: application/json

{
  "content" : "이건 삭제할 댓글입니다."
}

###
GET http://localhost:5500/articles/comments

###
GET http://localhost:5500/comments/products